events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    include       /etc/nginx/conf.d/*.conf;
    # include       /etc/nginx/sites-enabled/default;
    default_type  application/octet-stream;
    access_log syslog:server=logstash:5044;    
    # access_log  /var/log/nginx/access.log  main;
}
