input {
    syslog {
        port => 5044
        tags => "nginx"
    }
}
filter {
    grok {
        match => { "message" => "%{IPORHOST:remote_ip} - ${DATA:user_name} \[%{HTTPDATE:access_time}\] \"%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}\" 
        %{NUMBER:response_code} %{NUMBER:body_sent_bytes} \"%{DATA:refferer}\" \"%{DATA:agent}\"" }
    }
    mutate {
        remove_field => ["host"]
    }
}
output {
    if "nginx" in [tags] {
        elasticsearch {
            hosts => ["${ES_HOST}"]
            ssl_certificate_verification => false
            index => "nginx-index"
        }
    }
}