input {
    beats {
	port => 5044
    }
}

filter {
 grok {
   match => [ "message" , "%{COMBINEDAPACHELOG}+%{GREEDYDATA:extra_fields}"]
   overwrite => [ "message" ]
 }
 mutate {
   convert => ["response", "integer"]
   convert => ["bytes", "integer"]
   convert => ["responsetime", "float"]
 }
 geoip {
   source => "[source][address]"
   target => "geoip"
   database => "/etc/logstash/GeoLite2-City.mmdb"
   add_tag => [ "geoip" ]
 }
 date {
   match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss Z" ]
   remove_field => [ "timestamp" ]
 }
 mutate { remove_field => [ "message"] }
}

output {
 elasticsearch {
   hosts => ["https://192.168.56.40:9200","https://192.168.56.37:9200"]
   user => logstash_web
   password => Qwerty123
   ssl => true
   cacert => "/etc/logstash/http_ca.crt"
   index => "weblogs-%{+YYYY.MM.dd}"
 }
}